### PR TITLE
Allow psr/log 2.x and 3.x

### PR DESCRIPTION
**Pull request by msvrtan**
I'm being blocked by expectation that psr/log 1 is only supported. I'm not an expert here, not sure if this would be a problem?

If merged I would be very thankful if new version can be pushed tagged too

### CODE REVIEW

**Comment by ssi-anik** [comment]
@msvrtan thanks for the PR. Due to the change, tests are failing. Can you make the according changes? https://nerdpress.org/2022/03/04/class-psrlogtesttestlogger-not-found/

**Comment by stevenmaguire** [comment]
I am also running into an issue here. Perhaps, instead of making all three versions work in the same version, it is time for a new 3.x major version to uses more recent dependency versions only?

**Comment by ssi-anik** [comment]
@stevenmaguire I totally forgot about this PR. Okay. I will look into it and hopefully release a new version as proposed.

**Comment by stevenmaguire** [comment]
Wonderful! It's a useful package.

**Comment by ssi-anik** [comment]
Sorry for the delayed response. I have just created a new release with `v3.0`.

**Pull request merged**
